### ISSUE TITLE
Recomposition happens multiple time

### ISSUE THREAD

**Issue by Drjacky** [joreilly/FantasyPremierLeague#14]
`PlayerDetailsScreen` composable has been called multiple times;
Thus, https://github.com/joreilly/FantasyPremierLeague/blob/03e841ea3ae3e8be0fc4c2781f3b5f77d6d48bff/app/src/main/java/dev/johnoreilly/fantasypremierleague/MainActivity.kt#L83  
get called multiple times.
Is that okay?
Is there a way to prevent these multiple recompositions?

**Comment by HoinzeyBear** [comment]
I looked into this last night with the new layout inspector tool which counts recompositions and found nothing out of order, so I think this could be closed unless you want to confirm John
