### ISSUE TITLE
Crash on iOS when in airplane mode

### ISSUE THREAD

**Issue by IanArb** [joreilly/FantasyPremierLeague#20]
It seems the iOS is crashing due to an issue with ktor throwing an Exception. Been scratching my head around this one and Android is fine since you can always catch the exception there in platform specific code.

What would be the best approach to handle this? should it be done in shared code or platform specific? 

```
Uncaught Kotlin exception: io.ktor.client.engine.darwin.DarwinHttpRequestException: Exception in http request: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline."
```

Looks it was raised before. https://github.com/ktorio/ktor/issues/1165

**Comment by joreilly** [comment]
Yeah, quite likely there's some gaps there around error handling right now.  I'll take a look at improving this.

**Comment by joreilly** [comment]
Added code to at least catch exception when this occurs (will show what's in DB currently in that case).  Will look later at how best to surface this to UI and/or tie this in to some network state detection etc.
