### ISSUE TITLE
Extra loading ViewModel Data and SwiftUI navigation.

### ISSUE THREAD

**Issue by frankois944** [joreilly/FantasyPremierLeague#229]
Hi, thanks for the superb example.

I found a big issue for iOS, about loading data and navigation with SwiftUI.

For exemple :
```
val leagues: StateFlow<List<String>> = repository.leagues
    .stateIn(viewModelScope, SharingStarted.Eagerly, emptyList())
```
If I'm guessing correctly, each time the viewmodel is loaded, the property leagues is automattically loaded, because of  `SharingStarted.Eagerly`.

The big issue is on SwiftUI with navigationLink, the properties in the destination View are loaded even it's not appearing, so also the viewmodel, as intended in SwiftUI.

If inside a list, there is for each row a navigationLink, each row load the viewmodel and the linked data....

A fix should be :
```
val leagues: StateFlow<List<String>> = repository.leagues
    .stateIn(viewModelScope, SharingStarted.Lazily, emptyList())
```
So we're loading the data when the view is bind to the viewmodel property as intented in swiftUI.

If we don't want to touch the kotlin code, there is an another solution, it's to wrap the Kotlin ViewModel inside a `StateObject/ObservableObject` but it's making more swiftui code.

**Comment by joreilly** [comment]
Thanks for that.  Are you able to open PR with the change?

**Comment by frankois944** [comment]
Yes, I can do that
