### ISSUE TITLE
Not able to build the project in Android Studio with the latest version (4.1.2)

### ISSUE THREAD

**Issue by jawidMuhammadi** [joreilly/FantasyPremierLeague#7]
When I tried to build the project in Android Studio, I got this error: 
`
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.`

I tried the solution in the following StackOverflow questions but none of them is working:

1) https://stackoverflow.com/questions/53331462/this-version-of-android-studio-cannot-open-this-project-please-retry-with-andro
2) https://stackoverflow.com/questions/62678785/android-support-plugin-for-intellij-idea-or-android-studio-cannot-open-this-pr/65453722

**Comment by joreilly** [comment]
I probably need to update README for this repo  but right now projects with Jetpack Compose are only officially supported in Android Studio Canary versions.  I think it is possible to run them in other versions (though preview then won't work I believe).....but at least right now all the projects I have that use Compose need to be opened with Canary version.

**Comment by jawidMuhammadi** [comment]
@joreilly Thanks for your prompt response. I will try Canary Version then.

**Comment by karanDhillon** [comment]
Commit a8977b70b915fe11a84f1b54a8b3541e25068f37 solves this issue.
